### PR TITLE
fix sheep drops

### PR DESCRIPTION
**Pull request by AGTHARN**
sheep doesnt drop loot when it dies

### CODE REVIEW

**Comment by Heisenburger69** [comment]
Sheep only drop items when killed by a player, not sure if this is vanilla behavior, I'll add it into the next release if it is

**Comment by AGTHARN** [comment]
For some reason, when I tested it with that code, it dropped the wool and mutton. I'm not sure if it is caused by another plugin. It didn't seem to drop its loot without that code.

**Comment by AGTHARN** [comment]
I have just tested it again without any other plugins. With the changes made, sheep would drop its loot when it dies to lava. But without the changes, it wouldn't drop its loot. The change is almost similar to the cow, and the cow even drops its loot. You can try it yourself, it works.

**Comment by Heisenburger69** [comment]
oopsie, my bad

**Pull request merged**
