### PR TITLE
Auto Stack Implementation

### LINKED ISSUE #8: suggestion
up the radius u have to be in for the mobs to spawn from spawners, u have to be like within 5 blocks for the spawners to work

### PR DESCRIPTION
**Pull request by iZeaoGamer**
So since you liked my previous pull request, I thought I'd do another one. Also, I'm making this pull request because auto stack needs to be implemented. Otherwise, players can still lag out the server with spawners, or even lag the clients.
Without this implementation, players can possibly use it to their advantage, and abuse the system.

## What does this Pull request provide?
As previously stated, this pull request provides auto spawner stacking. Whenever a new spawner is placed of the same type as the previously placed, spawners will connect, stack, whatever you'd like to call it. When stacked, it will stay connected, allowing you, or the players to have an enjoyable time whilst grinding their way up to victory. Again, this is great for Factions and skyblock servers that do provide spawners.
Auto stack is also very useful because it prevents lag a ton. Yes, this plugin may well have prevented some or even a lot of the lag, but this feature should prevent lag a lot more than before.

## More fixes? Late fixes
I have recently fixed a bug, where spawn range would be 4 blocks to be exact. This was simply too short. Now, I don't know what it is in vanilla, so for now, I've put it to 16. I know it's a lot, but that's just temporary until if I know whether it's right or not. Because I'm assuming the person is referring to Spawn_range code from Issue #8.
This pull request fixes #8, which should be closed if this pull request fixes their issue. Not sure how complicated this would be though, I'm just assuming he's talking about Spawn range, since that was 4 blocks, and he stated around 5 blocks. Plus, the name seems similar to his issue. So I just went along with that.
This has also been tested to work with the latest versions of Pocketmine, and its latest plugin dev builds.

## Anything else we need to know about?
No, except I've bumped plugin version to v0.0.5.  I hope you don't mind.

## Coming soon
- Make spawn range configurable.

## PHP Stan Testing?
Everything's tested to work, no errors found.

## Any mentions?
I would once again, like to thank you for this awesome plugin! Truly means a lot to the MCPE and Pocketmine Community!

### CODE REVIEW

**Comment by Heisenburger69** [comment]
The Autostacking part looks great, thank you for working on that. There's two issues however:
1. #8 is in reference to the load range, not the spawn range. The spawn range value is the radius around which a Spawner Tile randomly spawns a mob. So with the value you set of 16, a new mob stack would spawn anywhere in a 16 block radius, which is quite large. #8 is talking about the Load_Range value, which is currently set to 15 so I'm not sure why that behavior occurs
2. Once the issue with Load_Range is fine, I don't plan to hardcode the value, I'll add it to the config in a later release once I identify the issue.

The PR looks great otherwise, thank you again!

**Comment by iZeaoGamer** [comment]
Okay, keep this pull request open until I make spawn range configurable. Since players can decide how far a mob spawns from the player’s render in blocks.

**Comment by iZeaoGamer** [comment]
Okay, done. Should be ready for merging, unless you have to say anything about issues that I added or made. Thank you!

**Comment by Heisenburger69** [comment]
This looks perfect, great job!

**Pull request merged**
